[theme]
base = "light"
primaryColor = "#ED2024"
dataframeHeaderBackgroundColor = "#ED2024"
font = "Montserrat:https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300..900;1,300..900&display=swap"

[theme.light]
backgroundColor = "#fcfcfb"
secondaryBackgroundColor = "#D8D2D2"
textColor = "#0b0b0b"

[theme.dark]
backgroundColor = "#1a1a19"
secondaryBackgroundColor = "#0d0d0d"
textColor = "#ffffff"
